abstract: authenticate people and read books!
author: and Copyright
build_requires: 
  Catalyst::Runtime: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: CatalystX-Controller-reCAPTCHA
no_index: 
  directory: 
    - inc
    - t
requires: 
  Captcha::reCAPTCHA: 0
  perl: 5.8.1
version: 0.1
